"""
load_to_snowflake.py
multisource-cde-mdr-pipeline | Day 2 — Snowflake load

Creates (or replaces) three tables in Snowflake and loads CSV data into them:
  - RAW.DOCUMENTS
  - STAGED.EVENTS
  - ANALYTICAL.MDR_REQUIREMENTS

Prerequisites:
  - .env file in project root with Snowflake credentials (see .env.example)
  - CSVs generated by the three generate_*.py scripts in data_generation/

Run from project root:
  python data_generation/load_to_snowflake.py

Or from inside data_generation/:
  python load_to_snowflake.py
"""

import csv
import os
from pathlib import Path
from dotenv import load_dotenv
import snowflake.connector

# ── Resolve paths ──────────────────────────────────────────────────────────────
SCRIPT_DIR   = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent

# .env lives in project root
load_dotenv(PROJECT_ROOT / ".env")

RAW_CSV     = SCRIPT_DIR / "raw_documents.csv"
STAGED_CSV  = SCRIPT_DIR / "staged_events.csv"
MDR_CSV     = SCRIPT_DIR / "mdr_requirements.csv"

# ── DDL — table definitions ────────────────────────────────────────────────────

DDL_RAW = """
CREATE OR REPLACE TABLE RAW.DOCUMENTS (
    -- Identity
    document_id              VARCHAR(36)   NOT NULL,
    source_system_id         VARCHAR(100)  NOT NULL,
    source_system            VARCHAR(50)   NOT NULL,
    source_system_instance   VARCHAR(100)  NOT NULL,
    -- Status
    source_status            VARCHAR(100),
    canonical_status         VARCHAR(50),
    iso19650_status_code     VARCHAR(5),
    -- ISO 19650-2 naming fields
    project_code             VARCHAR(20),
    originator_code          VARCHAR(20),
    volume_code              VARCHAR(10),
    level_code               VARCHAR(10),
    type_code                VARCHAR(5),
    role_code                VARCHAR(5),
    iso19650_filename        VARCHAR(200),
    -- Document metadata
    document_type            VARCHAR(100),
    discipline               VARCHAR(50),
    revision                 VARCHAR(10),
    title                    VARCHAR(500),
    description              TEXT,
    file_format              VARCHAR(10),
    -- Approval & certification
    approval_class           VARCHAR(20),
    certification_required   BOOLEAN,
    certifying_body          VARCHAR(100),
    certifying_body_contact  VARCHAR(200),
    -- Confidentiality (ISO 19650-5)
    confidentiality_class    VARCHAR(20),
    sensitive_information    BOOLEAN,
    -- People
    author                   VARCHAR(200),
    co_author                VARCHAR(200),
    originator_company       VARCHAR(200),
    reviewer                 VARCHAR(200),
    approver                 VARCHAR(200),
    -- Dates
    issue_date               DATE,
    ingested_at              TIMESTAMP_TZ,
    PRIMARY KEY (document_id)
);
"""

DDL_STAGED = """
CREATE OR REPLACE TABLE STAGED.EVENTS (
    event_id                 VARCHAR(36)   NOT NULL,
    document_id              VARCHAR(36)   NOT NULL,
    from_status              VARCHAR(50),
    to_status                VARCHAR(50),
    planned_timestamp        TIMESTAMP_TZ,
    actual_timestamp         TIMESTAMP_TZ,
    variance_days            INTEGER,
    days_in_previous_status  INTEGER,
    review_cycle             INTEGER,
    target_revision          VARCHAR(10),
    approval_class           VARCHAR(20),
    actioned_by_user_id      VARCHAR(20),
    actioned_by_name         VARCHAR(200),
    entered_by               VARCHAR(200),
    comments                 TEXT,
    PRIMARY KEY (event_id),
    FOREIGN KEY (document_id) REFERENCES RAW.DOCUMENTS(document_id)
);
"""

DDL_MDR = """
CREATE OR REPLACE TABLE ANALYTICAL.MDR_REQUIREMENTS (
    -- Identity
    mdr_id                      VARCHAR(20)   NOT NULL,
    fulfilled_by_document_id    VARCHAR(36),
    -- Document metadata (denormalised from RAW)
    document_title              VARCHAR(500),
    description                 TEXT,
    document_type               VARCHAR(100),
    discipline                  VARCHAR(50),
    current_revision            VARCHAR(10),
    file_format                 VARCHAR(10),
    -- ISO 19650
    iso19650_status_code        VARCHAR(5),
    iso19650_filename           VARCHAR(200),
    -- Approval & certification
    approval_class              VARCHAR(20),
    certification_required      BOOLEAN,
    certifying_body             VARCHAR(100),
    certifying_body_contact     VARCHAR(200),
    -- Confidentiality
    confidentiality_class       VARCHAR(20),
    sensitive_information       BOOLEAN,
    -- Responsibility (discipline lead)
    responsible_person          VARCHAR(200),
    responsible_company         VARCHAR(200),
    -- Priority & schedule
    priority                    VARCHAR(20),
    is_on_critical_path         BOOLEAN,
    planned_submission_date     DATE,
    planned_approval_date       DATE,
    -- Controlling fields
    current_canonical_status    VARCHAR(50),
    schedule_float_days         INTEGER,
    rag_status                  VARCHAR(10),
    -- Date trending
    baseline_approval_date      DATE,
    previous_approval_date      DATE,
    total_slip_days             INTEGER,
    recent_slip_days            INTEGER,
    date_trend                  VARCHAR(20),
    -- Progress
    derived_percent_complete    INTEGER,
    reported_percent_complete   INTEGER,
    -- Derived / linked
    source_system               VARCHAR(50),
    source_system_instance      VARCHAR(100),
    source_system_link          VARCHAR(500),
    last_status_change          TIMESTAMP_TZ,
    next_action                 VARCHAR(500),
    notes                       TEXT,
    PRIMARY KEY (mdr_id),
    FOREIGN KEY (fulfilled_by_document_id) REFERENCES RAW.DOCUMENTS(document_id)
);
"""

# ── Type coercion helpers ──────────────────────────────────────────────────────
def coerce_bool(val: str):
    """Convert string boolean representations to Python bool or None."""
    if val in ("True", "true", "1", "yes"):  return True
    if val in ("False", "false", "0", "no"): return False
    return None

def coerce_int(val: str):
    """Convert string to int or None."""
    try:    return int(val)
    except: return None

def coerce_ts(val: str):
    """Return ISO timestamp string or None."""
    return val.strip() if val.strip() else None

def coerce_date(val: str):
    """Return date string or None."""
    return val.strip() if val.strip() else None

# ── Load a CSV into a Snowflake table ────────────────────────────────────────
def load_csv(cursor, csv_path: Path, table: str, bool_fields: set, int_fields: set, ts_fields: set, date_fields: set):
    with open(csv_path, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        print(f"  ⚠ No rows in {csv_path}")
        return

    columns   = list(rows[0].keys())
    col_list  = ", ".join(columns)
    placeholders = ", ".join(["%s"] * len(columns))
    insert_sql = f"INSERT INTO {table} ({col_list}) VALUES ({placeholders})"

    batch = []
    for row in rows:
        values = []
        for col in columns:
            val = row[col]
            if col in bool_fields:   values.append(coerce_bool(val))
            elif col in int_fields:  values.append(coerce_int(val))
            elif col in ts_fields:   values.append(coerce_ts(val))
            elif col in date_fields: values.append(coerce_date(val))
            else:                    values.append(val if val != "" else None)
        batch.append(tuple(values))

    cursor.executemany(insert_sql, batch)
    print(f"  ✓ Loaded {len(batch)} rows → {table}")

# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    # Check CSVs exist
    for p in [RAW_CSV, STAGED_CSV, MDR_CSV]:
        if not p.exists():
            print(f"✗ Missing: {p}")
            print("  Run the three generate_*.py scripts first.")
            return

    # Connect to Snowflake
    print("Connecting to Snowflake...")
    try:
        connect_kwargs = {
            "user":      os.environ["SNOWFLAKE_USER"],
            "password":  os.environ["SNOWFLAKE_PASSWORD"],
            "account":   os.environ["SNOWFLAKE_ACCOUNT"],
            "warehouse": os.environ["SNOWFLAKE_WAREHOUSE"],
            "database":  os.environ["SNOWFLAKE_DATABASE"],
            "schema":    os.environ.get("SNOWFLAKE_SCHEMA"),
        }
        role = os.environ.get("SNOWFLAKE_ROLE")
        if role:
            connect_kwargs["role"] = role

        conn = snowflake.connector.connect(**connect_kwargs)
    except KeyError as e:
        print(f"✗ Missing environment variable: {e}")
        print("  Check your .env file against .env.example")
        return
    except Exception as e:
        print(f"✗ Snowflake connection failed: {e}")
        return

    cursor = conn.cursor()

    # Ensure database and schemas exist
    db = os.environ["SNOWFLAKE_DATABASE"]
    print("\nCreating database if not exists...")
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS {db}")
    cursor.execute(f"USE DATABASE {db}")

    print("\nCreating schemas if not exists...")
    for schema in ["RAW", "STAGED", "ANALYTICAL"]:
        cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # Create tables
    print("\nCreating tables...")
    for name, ddl in [("RAW.DOCUMENTS", DDL_RAW), ("STAGED.EVENTS", DDL_STAGED), ("ANALYTICAL.MDR_REQUIREMENTS", DDL_MDR)]:
        cursor.execute(ddl)
        print(f"  ✓ Table {name}")

    # Load data
    print("\nLoading data...")

    load_csv(
        cursor, RAW_CSV, "RAW.DOCUMENTS",
        bool_fields  = {"certification_required", "sensitive_information"},
        int_fields   = set(),
        ts_fields    = {"ingested_at"},
        date_fields  = {"issue_date"},
    )

    load_csv(
        cursor, STAGED_CSV, "STAGED.EVENTS",
        bool_fields  = set(),
        int_fields   = {"variance_days", "days_in_previous_status", "review_cycle"},
        ts_fields    = {"planned_timestamp", "actual_timestamp"},
        date_fields  = set(),
    )

    load_csv(
        cursor, MDR_CSV, "ANALYTICAL.MDR_REQUIREMENTS",
        bool_fields  = {"certification_required", "sensitive_information", "is_on_critical_path"},
        int_fields   = {"schedule_float_days", "total_slip_days", "recent_slip_days",
                        "derived_percent_complete", "reported_percent_complete"},
        ts_fields    = {"last_status_change"},
        date_fields  = {"planned_submission_date", "planned_approval_date",
                        "baseline_approval_date", "previous_approval_date"},
    )

    conn.commit()
    cursor.close()
    conn.close()
    print("\n✓ All done. Snowflake load complete.")
    print(f"  Database : {os.environ['SNOWFLAKE_DATABASE']}")
    print(f"  Tables   : RAW.DOCUMENTS, STAGED.EVENTS, ANALYTICAL.MDR_REQUIREMENTS")

if __name__ == "__main__":
    main()
