"""
load_to_snowflake.py
multisource-cde-mdr-pipeline

Creates (or replaces) seven tables in Snowflake and loads CSV data into them:

  RAW layer — source-native schemas, one table per source system:
    RAW.WINDCHILL_DOCUMENTS   (30 rows — Windchill field names, ISO dates, A/B/C revisions)
    RAW.SHAREPOINT_DOCUMENTS  (20 rows — SharePoint field names, MM/DD/YYYY dates, 1.0/2.0 versions)
    RAW.AVEVA_DOCUMENTS       (10 rows — Aveva field names, DD.MM.YYYY dates, numeric revisions)

  STAGED layer — harmonised pipeline outputs:
    STAGED.EVENTS             (~510 rows — canonical ISO 19650 IDs, normalised schema)
    STAGED.DQ_FLAGS           (~15 rows — data quality issues flagged at pipeline run time)

  ANALYTICAL layer — dashboard-facing tables:
    ANALYTICAL.MDR_REQUIREMENTS (60 rows — schedule, RAG status, delivery visibility)
    ANALYTICAL.EDIT_LOG         (append-only audit trail of all user edits and DQ resolutions)

The RAW tables deliberately preserve source-native field names and date formats.
The STAGED layer is where all harmonisation happens — the schema difference is the demo point.

Prerequisites:
  - .env file in project root with Snowflake credentials (see .env.example)
  - All CSVs generated by the generate_*.py scripts in data_generation/

Run from project root:
  python data_generation/load_to_snowflake.py

Or from inside data_generation/:
  python load_to_snowflake.py
"""

import csv
import os
from pathlib import Path
from dotenv import load_dotenv
import snowflake.connector

# ── Resolve paths ──────────────────────────────────────────────────────────────
SCRIPT_DIR   = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent

# .env lives in project root
load_dotenv(PROJECT_ROOT / ".env")

# Source-native CSVs (RAW layer)
WC_CSV     = SCRIPT_DIR / "windchill_source.csv"
SP_CSV     = SCRIPT_DIR / "sharepoint_source.csv"
AVEVA_CSV  = SCRIPT_DIR / "aveva_source.csv"

# Pipeline output CSVs (STAGED and ANALYTICAL layers)
STAGED_CSV  = SCRIPT_DIR / "staged_events.csv"
DQ_CSV      = SCRIPT_DIR / "staged_dq_flags.csv"
MDR_CSV     = SCRIPT_DIR / "mdr_requirements.csv"
# Edit log lives in dashboard/ — it is written by the dashboard at runtime, not by the pipeline
EDITLOG_CSV = PROJECT_ROOT / "dashboard" / "edit_log.csv"

# ── DDL — RAW layer: source-native tables ─────────────────────────────────────
# These tables store data exactly as it came out of each source system.
# Field names, date formats, and revision schemes are preserved as-is.
# The STAGED layer is responsible for harmonising all of this.

DDL_WC = """
CREATE OR REPLACE TABLE RAW.WINDCHILL_DOCUMENTS (
    -- Instance and identity (Windchill-native field names)
    wc_instance              VARCHAR(100)  NOT NULL,
    wc_id                    VARCHAR(50)   NOT NULL,
    wc_doc_number            VARCHAR(100),
    -- Status and revision (A/B/C scheme)
    wc_lifecycle_state       VARCHAR(100),
    wc_revision              VARCHAR(10),
    -- Dates (ISO 8601 format: 2025-12-19T17:57:34Z)
    wc_created_at            TIMESTAMP_TZ,
    wc_modified_at           TIMESTAMP_TZ,
    -- People
    wc_author                VARCHAR(200),
    wc_co_author             VARCHAR(200),
    wc_reviewer              VARCHAR(200),
    wc_approver              VARCHAR(200),
    -- Classification (MECH/ELEC/INST discipline codes)
    wc_discipline_code       VARCHAR(20),
    wc_document_type         VARCHAR(100),
    wc_originator_company    VARCHAR(200),
    wc_originator_code       VARCHAR(20),
    wc_confidentiality       VARCHAR(50),
    wc_approval_class        VARCHAR(20),
    wc_certifying_body       VARCHAR(100),
    wc_certification_required BOOLEAN,
    wc_file_format           VARCHAR(10),
    PRIMARY KEY (wc_id)
);
"""

DDL_SP = """
CREATE OR REPLACE TABLE RAW.SHAREPOINT_DOCUMENTS (
    -- Instance and identity (SharePoint-native field names)
    sp_instance              VARCHAR(100)  NOT NULL,
    sp_item_id               INTEGER       NOT NULL,
    sp_file_name             VARCHAR(500),
    -- Status and version (1.0/2.0 scheme — note: not A/B/C like Windchill)
    sp_status                VARCHAR(100),
    sp_version               VARCHAR(10),
    -- Dates (MM/DD/YYYY format — deliberately different from Windchill and Aveva)
    sp_created               VARCHAR(20),
    sp_modified              VARCHAR(20),
    -- People
    sp_created_by            VARCHAR(200),
    sp_modified_by           VARCHAR(200),
    sp_reviewer              VARCHAR(200),
    -- Classification (verbose department names, e.g. "Mechanical Engineering")
    sp_department            VARCHAR(100),
    sp_document_category     VARCHAR(100),
    sp_company               VARCHAR(200),
    sp_classification        VARCHAR(50),
    sp_approval_type         VARCHAR(50),
    sp_certifying_body       VARCHAR(100),
    sp_certification_required BOOLEAN,
    sp_file_type             VARCHAR(10),
    PRIMARY KEY (sp_item_id)
);
"""

DDL_AVEVA = """
CREATE OR REPLACE TABLE RAW.AVEVA_DOCUMENTS (
    -- Instance and identity (Aveva-native field names)
    aveva_instance           VARCHAR(100)  NOT NULL,
    aveva_id                 VARCHAR(50)   NOT NULL,
    aveva_doc_number         VARCHAR(100),
    aveva_tag_ref            VARCHAR(100),
    -- Status and revision (numeric 0/1/2 scheme)
    aveva_document_status    VARCHAR(100),
    aveva_revision_no        INTEGER,
    -- Dates (DD.MM.YYYY format — deliberately different from Windchill and SharePoint)
    aveva_issue_date         VARCHAR(20),
    aveva_last_updated       VARCHAR(30),
    -- People
    aveva_prepared_by        VARCHAR(200),
    aveva_checked_by         VARCHAR(200),
    aveva_approved_by        VARCHAR(200),
    -- Classification (I&C discipline code — normalisation issue flagged by pipeline)
    aveva_discipline         VARCHAR(50),
    aveva_doc_class          VARCHAR(10),
    aveva_doc_type           VARCHAR(100),
    aveva_originator_org     VARCHAR(200),
    aveva_security_class     VARCHAR(50),
    aveva_approval_category  VARCHAR(50),
    aveva_certifying_body    VARCHAR(100),
    aveva_certification_required BOOLEAN,
    aveva_file_format        VARCHAR(10),
    PRIMARY KEY (aveva_id)
);
"""

# ── DDL — STAGED layer ────────────────────────────────────────────────────────
# Harmonised event log. All three source systems feed into this single table.
# mdr_id is the canonical ISO 19650 document identifier assigned by the pipeline.

DDL_STAGED = """
CREATE OR REPLACE TABLE STAGED.EVENTS (
    event_id                 VARCHAR(36)   NOT NULL,
    document_id              VARCHAR(36)   NOT NULL,
    from_status              VARCHAR(50),
    to_status                VARCHAR(50),
    planned_timestamp        TIMESTAMP_TZ,
    actual_timestamp         TIMESTAMP_TZ,
    variance_days            INTEGER,
    days_in_previous_status  INTEGER,
    review_cycle             INTEGER,
    target_revision          VARCHAR(10),
    approval_class           VARCHAR(20),
    actioned_by_user_id      VARCHAR(20),
    actioned_by_name         VARCHAR(200),
    entered_by               VARCHAR(200),
    comments                 TEXT,
    PRIMARY KEY (event_id)
);
"""

# ── DDL — STAGED.DQ_FLAGS ────────────────────────────────────────────────────
# Data quality issues flagged by the pipeline at staged layer run time.
# resolved/resolved_by/resolved_at are populated by the Document Controller
# via the dashboard remediation queue. This table shows stale state until
# load_to_snowflake.py is rerun — that staleness is intentional in the demo.

DDL_DQ = """
CREATE OR REPLACE TABLE STAGED.DQ_FLAGS (
    flag_id          VARCHAR(20)   NOT NULL,
    mdr_id           VARCHAR(60),
    source_system    VARCHAR(50),
    source_native_id VARCHAR(100),
    field_name       VARCHAR(100),
    flag_type        VARCHAR(50),
    flag_detail      TEXT,
    original_value   VARCHAR(500),
    suggested_value  VARCHAR(500),
    resolved         BOOLEAN,
    resolved_by      VARCHAR(200),
    resolved_at      TIMESTAMP_TZ,
    resolved_value   VARCHAR(500),
    PRIMARY KEY (flag_id)
);
"""

# ── DDL — ANALYTICAL.EDIT_LOG ─────────────────────────────────────────────────
# Append-only audit trail written by the dashboard for every user action:
# PM_UPDATE events (priority, critical path, percent complete, notes) and
# DQ_REMEDIATION events (DC resolving a flagged field).
# The 'field' column encodes event type, e.g. "dq_flag_resolved:DQF-0001".

DDL_EDITLOG = """
CREATE OR REPLACE TABLE ANALYTICAL.EDIT_LOG (
    timestamp  TIMESTAMP_TZ,
    username   VARCHAR(200),
    mdr_id     VARCHAR(60),
    field      VARCHAR(200),
    old_value  TEXT,
    new_value  TEXT
);
"""

# ── DDL — ANALYTICAL layer ────────────────────────────────────────────────────
# MDR register built from STAGED outputs. This is what the dashboard reads.

DDL_MDR = """
CREATE OR REPLACE TABLE ANALYTICAL.MDR_REQUIREMENTS (
    -- Identity
    mdr_id                      VARCHAR(60)   NOT NULL,
    fulfilled_by_document_id    VARCHAR(36),
    -- Document metadata (denormalised from RAW for dashboard performance)
    document_title              VARCHAR(500),
    description                 TEXT,
    document_type               VARCHAR(100),
    discipline                  VARCHAR(50),
    current_revision            VARCHAR(10),
    file_format                 VARCHAR(10),
    -- ISO 19650
    iso19650_status_code        VARCHAR(5),
    iso19650_filename           VARCHAR(200),
    -- Approval & certification
    approval_class              VARCHAR(20),
    certification_required      BOOLEAN,
    certifying_body             VARCHAR(100),
    certifying_body_contact     VARCHAR(200),
    -- Confidentiality
    confidentiality_class       VARCHAR(20),
    sensitive_information       BOOLEAN,
    -- Responsibility (discipline lead)
    responsible_person          VARCHAR(200),
    responsible_company         VARCHAR(200),
    -- Priority & schedule
    priority                    VARCHAR(20),
    is_on_critical_path         BOOLEAN,
    planned_submission_date     DATE,
    planned_approval_date       DATE,
    -- Controlling fields
    current_canonical_status    VARCHAR(50),
    schedule_float_days         INTEGER,
    rag_status                  VARCHAR(10),
    -- Date trending
    baseline_approval_date      DATE,
    previous_approval_date      DATE,
    total_slip_days             INTEGER,
    recent_slip_days            INTEGER,
    date_trend                  VARCHAR(20),
    -- Progress
    derived_percent_complete    INTEGER,
    reported_percent_complete   INTEGER,
    -- Derived / linked
    source_system               VARCHAR(50),
    source_system_instance      VARCHAR(100),
    source_system_link          VARCHAR(500),
    last_status_change          TIMESTAMP_TZ,
    next_action                 VARCHAR(500),
    notes                       TEXT,
    PRIMARY KEY (mdr_id)
);
"""

# ── Type coercion helpers ──────────────────────────────────────────────────────

def coerce_bool(val: str):
    """Convert string boolean representations to Python bool or None."""
    if val in ("True", "true", "1", "yes"):  return True
    if val in ("False", "false", "0", "no"): return False
    return None

def coerce_int(val: str):
    """Convert string to int or None."""
    try:    return int(val)
    except: return None

def coerce_ts(val: str):
    """Return ISO timestamp string or None (empty string -> None)."""
    return val.strip() if val.strip() else None

def coerce_date(val: str):
    """Return date string or None (empty string -> None)."""
    return val.strip() if val.strip() else None

# ── Load a CSV into a Snowflake table ────────────────────────────────────────

def load_csv(cursor, csv_path: Path, table: str,
             bool_fields: set, int_fields: set, ts_fields: set, date_fields: set):
    """
    Read a CSV and insert all rows into the given Snowflake table.

    The column list is derived from the CSV header, so the CSV columns must
    match the table DDL exactly. Type coercion is applied per field set.

    Args:
        cursor:       Snowflake cursor
        csv_path:     Path to the CSV file
        table:        Fully qualified table name (e.g. "RAW.WINDCHILL_DOCUMENTS")
        bool_fields:  Column names that should be coerced to BOOLEAN
        int_fields:   Column names that should be coerced to INTEGER
        ts_fields:    Column names that are TIMESTAMP_TZ (passed as ISO strings)
        date_fields:  Column names that are DATE (passed as date strings)
    """
    with open(csv_path, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        print(f"  WARN: No rows in {csv_path.name}")
        return

    columns      = list(rows[0].keys())
    col_list     = ", ".join(columns)
    placeholders = ", ".join(["%s"] * len(columns))
    insert_sql   = f"INSERT INTO {table} ({col_list}) VALUES ({placeholders})"

    batch = []
    for row in rows:
        values = []
        for col in columns:
            val = row[col]
            if col in bool_fields:   values.append(coerce_bool(val))
            elif col in int_fields:  values.append(coerce_int(val))
            elif col in ts_fields:   values.append(coerce_ts(val))
            elif col in date_fields: values.append(coerce_date(val))
            else:                    values.append(val if val != "" else None)
        batch.append(tuple(values))

    cursor.executemany(insert_sql, batch)
    print(f"  [SNOWFLAKE] Loaded {len(batch)} rows -> {table}")

# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    """Connect to Snowflake, create the schema, and load all five tables."""

    # Verify all required CSVs exist before connecting.
    # edit_log.csv is optional — it may be empty if no user edits have been made yet.
    required = {
        "windchill_source.csv":  WC_CSV,
        "sharepoint_source.csv": SP_CSV,
        "aveva_source.csv":      AVEVA_CSV,
        "staged_events.csv":     STAGED_CSV,
        "staged_dq_flags.csv":   DQ_CSV,
        "mdr_requirements.csv":  MDR_CSV,
    }
    missing = [name for name, path in required.items() if not path.exists()]
    if missing:
        for name in missing:
            print(f"[ERROR] Missing: {name}")
        print("  Run the generate_*.py scripts first.")
        return
    if not EDITLOG_CSV.exists():
        print("  WARN: dashboard/edit_log.csv not found — ANALYTICAL.EDIT_LOG will be empty")

    # Connect to Snowflake
    print("[SNOWFLAKE] Connecting...")
    try:
        connect_kwargs = {
            "user":      os.environ["SNOWFLAKE_USER"],
            "password":  os.environ["SNOWFLAKE_PASSWORD"],
            "account":   os.environ["SNOWFLAKE_ACCOUNT"],
            "warehouse": os.environ["SNOWFLAKE_WAREHOUSE"],
            "database":  os.environ["SNOWFLAKE_DATABASE"],
            "schema":    os.environ.get("SNOWFLAKE_SCHEMA"),
        }
        role = os.environ.get("SNOWFLAKE_ROLE")
        if role:
            connect_kwargs["role"] = role

        conn = snowflake.connector.connect(**connect_kwargs)
    except KeyError as e:
        print(f"[ERROR] Missing environment variable: {e}")
        print("  Check your .env file against .env.example")
        return
    except Exception as e:
        print(f"[ERROR] Snowflake connection failed: {e}")
        return

    cursor = conn.cursor()
    db = os.environ["SNOWFLAKE_DATABASE"]

    # Ensure database and schemas exist
    print(f"[SNOWFLAKE] Using database {db}")
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS {db}")
    cursor.execute(f"USE DATABASE {db}")
    for schema in ["RAW", "STAGED", "ANALYTICAL"]:
        cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # Create tables (CREATE OR REPLACE — safe to rerun)
    print("[SNOWFLAKE] Creating tables...")
    table_ddls = [
        ("RAW.WINDCHILL_DOCUMENTS",      DDL_WC),
        ("RAW.SHAREPOINT_DOCUMENTS",     DDL_SP),
        ("RAW.AVEVA_DOCUMENTS",          DDL_AVEVA),
        ("STAGED.EVENTS",                DDL_STAGED),
        ("STAGED.DQ_FLAGS",              DDL_DQ),
        ("ANALYTICAL.MDR_REQUIREMENTS",  DDL_MDR),
        ("ANALYTICAL.EDIT_LOG",          DDL_EDITLOG),
    ]
    for name, ddl in table_ddls:
        cursor.execute(ddl)
        print(f"  [SNOWFLAKE] Table {name} created or replaced")

    # Load data — RAW layer first (source-native, one table per system)
    print("\n[SNOWFLAKE] Loading RAW layer...")
    load_csv(
        cursor, WC_CSV, "RAW.WINDCHILL_DOCUMENTS",
        bool_fields  = {"wc_certification_required"},
        int_fields   = set(),
        ts_fields    = {"wc_created_at", "wc_modified_at"},
        date_fields  = set(),
    )
    load_csv(
        cursor, SP_CSV, "RAW.SHAREPOINT_DOCUMENTS",
        bool_fields  = {"sp_certification_required"},
        int_fields   = {"sp_item_id"},
        ts_fields    = set(),
        date_fields  = set(),
        # sp_created and sp_modified are stored as VARCHAR — MM/DD/YYYY format preserved intentionally
    )
    load_csv(
        cursor, AVEVA_CSV, "RAW.AVEVA_DOCUMENTS",
        bool_fields  = {"aveva_certification_required"},
        int_fields   = {"aveva_revision_no"},
        ts_fields    = set(),
        date_fields  = set(),
        # aveva_issue_date and aveva_last_updated stored as VARCHAR — DD.MM.YYYY format preserved intentionally
    )

    # Load STAGED layer (harmonised event log + DQ flags)
    print("\n[SNOWFLAKE] Loading STAGED layer...")
    load_csv(
        cursor, STAGED_CSV, "STAGED.EVENTS",
        bool_fields  = set(),
        int_fields   = {"variance_days", "days_in_previous_status", "review_cycle"},
        ts_fields    = {"planned_timestamp", "actual_timestamp"},
        date_fields  = set(),
    )
    load_csv(
        cursor, DQ_CSV, "STAGED.DQ_FLAGS",
        bool_fields  = {"resolved"},
        int_fields   = set(),
        ts_fields    = {"resolved_at"},
        date_fields  = set(),
    )

    # Load ANALYTICAL layer (MDR register + audit trail)
    print("\n[SNOWFLAKE] Loading ANALYTICAL layer...")
    load_csv(
        cursor, MDR_CSV, "ANALYTICAL.MDR_REQUIREMENTS",
        bool_fields  = {"certification_required", "sensitive_information", "is_on_critical_path"},
        int_fields   = {"schedule_float_days", "total_slip_days", "recent_slip_days",
                        "derived_percent_complete", "reported_percent_complete"},
        ts_fields    = {"last_status_change"},
        date_fields  = {"planned_submission_date", "planned_approval_date",
                        "baseline_approval_date", "previous_approval_date"},
    )
    # edit_log.csv may not exist yet if no user edits have been made
    if EDITLOG_CSV.exists():
        load_csv(
            cursor, EDITLOG_CSV, "ANALYTICAL.EDIT_LOG",
            bool_fields  = set(),
            int_fields   = set(),
            ts_fields    = {"timestamp"},
            date_fields  = set(),
        )
    else:
        print("  WARN: dashboard/edit_log.csv not found — ANALYTICAL.EDIT_LOG left empty")

    conn.commit()
    cursor.close()
    conn.close()
    print("\n[SNOWFLAKE] Load complete.")
    print(f"  Database : {db}")
    print(f"  RAW      : WINDCHILL_DOCUMENTS, SHAREPOINT_DOCUMENTS, AVEVA_DOCUMENTS")
    print(f"  STAGED   : EVENTS, DQ_FLAGS")
    print(f"  ANALYTICAL: MDR_REQUIREMENTS, EDIT_LOG")

if __name__ == "__main__":
    main()
